before_script:
  - export SERVICE_VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}

variables:
  GO_VERSION: '1.25'
  GOLANGCI_VERSION: 'v2.11'

stages:
  - test

.test:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

lint:
  extends:
    - .test
  image: docker-registry.selectel.ru/golangci/golangci-lint:$GOLANGCI_VERSION
  tags:
    - kube-dev
  script:
    - make lint

unit-tests:
  extends:
    - .test
  image: docker-registry.selectel.ru/library/golang:$GO_VERSION
  tags:
    - kube-dev
  script:
    - go test -coverprofile=coverage_unit.txt -covermode count -coverpkg=./pkg/... ./pkg/...
  artifacts:
    name: cover
    paths:
      - coverage_unit.txt

test-coverage:
  extends:
    - .test
  needs:
    - unit-tests
  dependencies:
    - unit-tests
  image: docker-registry.selectel.ru/library/golang:$GO_VERSION
  tags:
    - kube-dev
  script:
    - go install github.com/boumenot/gocover-cobertura@v1.4.0
    - gocover-cobertura -ignore-gen-files < coverage_unit.txt > coverage.xml
    - go tool cover -func coverage_unit.txt
  coverage: /total:\s+\(statements\)\s+\d+.\d+%/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  allow_failure: true
